build clr

diff --git a/rocm-dev/rd-build-clr b/rocm-dev/rd-build-clr
--- a/rocm-dev/rd-build-clr
+++ b/rocm-dev/rd-build-clr
@@ -20,6 +20,10 @@ if ! rd-helper -c "amd-staging"; then
     die "fail: clone clr/hip/hip-tests"
 fi
 
-if ! rd-helper -b "clr"; then
-    die "fail: build clr"
+if ! rd-helper -b "all"; then
+    die "fail: build clr/hip-tests"
+fi
+
+if ! cmake_install "./clr/build-release"; then
+    die "fail: install clr"
 fi
diff --git a/rocm-dev/rd-build-rocprofiler-sdk b/rocm-dev/rd-build-rocprofiler-sdk
--- a/rocm-dev/rd-build-rocprofiler-sdk
+++ b/rocm-dev/rd-build-rocprofiler-sdk
@@ -17,23 +17,44 @@ if ! is_docker_instance "$instance_name_rd" && ! is_docker_instance "$instance_n
     die "fail: please run it at instance: $instance_name_rd or $instance_name_sv"
 fi
 
-# rocprofiler-sdk, pull 634
-setup_repo `
+# rocprofiler-sdk
+if ! setup_repo `
     `"rocprofiler-sdk" `
     `"./rocprofiler-sdk" `
     `"https://github.com/ROCm/rocprofiler-sdk.git" `
-    `"amd-staging"
+    `"amd-staging"; then
+    die "fail: clone rocprofiler-sdk"
+fi
 
-cmake_build "./rocprofiler-sdk" "all" `
+if ! cmake_build "./rocprofiler-sdk" "all" `
     `-DCMAKE_INSTALL_PREFIX=$ROCM_PATH `
-    `-DCMAKE_PREFIX_PATH=$ROCM_PATH
+    `-DCMAKE_PREFIX_PATH=$ROCM_PATH; then
+    die "fail: build rocprofiler-sdk"
+fi
+
+if ! cmake_install ./rocprofiler-sdk/build/release; then
+    die "fail: install rocprofiler-sdk"
+fi
 
 # aqlprofile, pull 171
-setup_repo `
+if ! setup_repo `
     `"aqlprofile" `
     `"./aqlprofile" `
     `"git@github.com:AMD-ROCm-Internal/aqlprofile" `
-    `"amd-staging"
+    `"amd-staging"; then
+    die "fail: clone aqlprofile"
+fi
 
-cmake_build "./aqlprofile" "all" `
-    `CMAKE_PREFIX_PATH=${ROCM_PATH}/lib:${ROCM_PATH}/include/hsa
+if ! cmake_build "./aqlprofile" "all" `
+    `CMAKE_PREFIX_PATH=${ROCM_PATH}/lib:${ROCM_PATH}/include/hsa; then
+    die "fail: build aqlprofile"
+fi
+
+if ! cmake_install ./aqlprofile/build/release; then
+    die "fail: install aqlprofile"
+fi
+
+# download and install: rocprof-trace-decoder-ubuntu-22.04-x.x.x-Linux.deb from:
+# https://github.com/ROCm/rocprof-trace-decoder/releases
+
+# host: sv-update
diff --git a/scripts/rd-helper b/scripts/rd-helper
--- a/scripts/rd-helper
+++ b/scripts/rd-helper
@@ -147,21 +147,26 @@ function build_clr(){
 
 function build_hip_tests() {
     # hip-tests
-    local HIPTESTS_BUILD="${HIPTESTS_DIR}/build"
-    refresh_dir "$HIPTESTS_BUILD"
-    pushd "$HIPTESTS_BUILD"
-    if ! cmake ../catch `
-         `-DHIP_PLATFORM=amd `
-         `-DHIP_PATH=/opt/rocm; then
-         die "cmake fail: hip-tests"
-    fi
-    log "cmake successfuly: hip-tests"
+    local builds="Release Debug"
+    local cmake_options="-DHIP_PLATFORM=amd `
+                        `-DHIP_PATH=/opt/rocm"
+    local build
+    for build in $builds; do
+        local HIPTESTS_BUILD="${HIPTESTS_DIR}/build-${build,,}"
+        local dbg_option="-DCMAKE_BUILD_TYPE=$build"
+        refresh_dir "$HIPTESTS_BUILD"
+        pushd "$HIPTESTS_BUILD"
+        if ! cmake ../catch $cmake_options $dbg_option; then
+            die "cmake fail: hip-tests"
+        fi
+        log "cmake successfuly: hip-tests"
 
-    if ! make build_tests -j $(nproc); then
-        die "make fail: hip-tests"
-    fi
-    log "make successfuly: hip-tests"
-    popd
+        if ! make build_tests -j $(nproc); then
+            die "make fail: hip-tests"
+        fi
+        log "make successfuly: hip-tests"
+        popd
+    done
 }
 
 function build_component() {
@@ -176,7 +181,7 @@ function build_component() {
 
 function unit_test() {
     local group="$1"
-    local path="${HIPTESTS_DIR}/build/catch_tests/unit"
+    local path="${HIPTESTS_DIR}/build-release/catch_tests/unit"
     if [[ ! -d "$path" ]]; then
         die "unit test not found: $path"
     fi
