rd build

diff --git a/rocm-dev/rd-build-solver b/rocm-dev/rd-build-solver
--- a/rocm-dev/rd-build-solver
+++ b/rocm-dev/rd-build-solver
@@ -8,7 +8,6 @@ SELF_TAG="[$(basename $0)]"
 
 # import tools
 source docker-helper
-source cmake-helper
 source rd-config
 source sv-config
 
@@ -22,7 +21,7 @@ function clone_component() {
     local branch=${1#*/}
 
     log "clone: $comp"
-    local src_dir=$(realpath ${solver_src_root})/${comp}    
+    local src_dir=$(realpath ${solver_src_root})/${comp,,}    
     refresh_dir "${src_dir}"
     local rocm_url="https://github.com/ROCm/${comp}"
     if ! git clone "${rocm_url}" -b ${branch} ${src_dir}; then
@@ -33,120 +32,69 @@ function clone_component() {
 function build_component() {
     local comp=${1%/*}
     local branch=${1#*/}
-    local src_dir=$(realpath ${solver_src_root})/${comp}
+    local src_dir=$(realpath ${solver_src_root})/${comp,,}
 
     pushd "$src_dir"
     if [[ "$comp" == "rocPRIM" ]]; then
-        # rocPrim constains include files only
         # build and install
-        if ! elevate_if_not_root ./install -i; then
+        if ! elevate_if_not_root ./install -ri; then
             die "fail: build and install $comp"
         fi
-
-        # create deb pkg
-        pushd "./build/release"
-        if ! elevate_if_not_root cpack; then
-            die "fail: $comp cpack"
-        fi
-        cp *.deb "$pkg_dir/rel" 
-        cp *.deb "$pkg_dir/dbg"
-        popd
     elif [[ "$comp" == "hipBLAS-common" ]]; then
-        # hipBLAS-common constains include files only
-        refresh_dir ./build 
-        pushd ./build
-        if ! cmake ..; then
-            die "fail: build $comp"
+        if ! cmake -S . -B ./build; then
+            die "fail: cmake $comp"
         fi
 
-        # build and create deb pkg
-        if ! elevate_if_not_root make package install; then
+        # build and install
+        pushd ./build
+        if ! elevate_if_not_root make install; then
             die "fail: build pkg and install $comp"
         fi
-        cp *.deb "$pkg_dir/rel" 
-        cp *.deb "$pkg_dir/dbg"
         popd
     elif [[ "$comp" == "hipBLASLt" || "$comp" == "rocBLAS" ]]; then
-        # release build and install
-        if ! ./install.sh -di; then
+        # release and depencies
+        if ! ./install.sh -rd; then
             die "fail: build and install $comp"
         fi
-        cp ./build/release/*.deb "$pkg_dir/rel" 
 
-        # debug build
-        if ! ./install.sh -g; then
-            die "fail: build and install $comp"
-        fi
-        pushd "./build/debug"
-        cpack
-        cp ./build/release/*.deb "$pkg_dir/dbg" 
+        # install release
+        pushd ./build/release
+        sudo make install
         popd
 
-        # patch: pkg conflictions while installing *.deb
-        # todo: align the pkg version with current os to avoid the confliction ?
-        elevate_if_not_root apt --fix-broken install -y
+        # debug
+        if ! ./install.sh -rg; then
+            die "fail: build and install $comp"
+        fi
+    elif [[ "$comp" == "rocSOLVER" ]]; then
+        # release build depencies, no optimization
+        if ! ./install.sh -rcnd; then
+            die "fail: build and install $comp"
+        fi
+        # install release
+        pushd ./build/release
+        sudo make install
+        popd
+
+        # debug
+        if ! ./install.sh -rgn; then
+            die "fail: build and install $comp"
+        fi
     fi
-
-
     popd
 }
 
-pkg_dir="$(realpath ${solver_src_root})/pkg"
-refresh_dir "$pkg_dir/rel"
-refresh_dir "$pkg_dir/dbg"
+components="rocPRIM/develop `
+           `hipBLAS-common/develop `
+           `hipBLASLt/develop `
+           `rocBLAS/develop `
+           `rocSOLVER/develop"
 
-# rocPRIM/develop `
-# `hipBLAS-common/develop `
-# `hipBLASLt/develop `
-
-for curr in rocBLAS/develop `
-            `rocSOLVER/develop; do
-    # clone_component "$curr"
-    build_component "$curr"
-
+for curr in  $components; do
+    clone_component "$curr"
 done
 
-exit 0
-# rocblas
-# clone 
-log "build: rocblas"
-blas_src=$(realpath ./rocblas)
-refresh_dir "$blas_src"
-if ! git clone -b "$blas_branch" https://github.com/ROCm/rocBLAS.git "$blas_src"; then
-    die "fail: clone rocblas $blas_branch"
-fi
-
-pushd "$blas_src"
-# build dependency and  release 
-if ! ./install.sh -d; then
-    die "fail: build release rocblas $blas_branch"
-fi
-
-# build debug
-if ! ./install.sh --debug; then
-    die "fail: build release rocblas $blas_branch"
-fi
-popd
-log "build: rocblas success"
-
-# rocsolver
-# clone 
-log "build: rocsolver"
-solve_src=$(realpath ./rocsolver)
-refresh_dir "$solve_src"
-if ! git clone -b "$solve_branch" git@github.com:ROCm/rocSOLVER.git "$solve_src"; then
-    die "fail: clone rocsolver $blas_branch"
-fi
-
-pushd "$solve_src"
-# build dependency and  release 
-if ! ./install.sh -d; then
-    die "fail: build release rocsolver $solve_branch"
-fi
-
-# build debug
-if ! ./install.sh --debug; then
-    die "fail: build release rocsolver $solve_branch"
-fi
-popd
-log "build: rocsolver success"
+for curr in  $components; do
+    build_component "$curr"
+done
+return 0
