minor: host alias

diff --git a/rocm-dev/rd-open b/rocm-dev/rd-open
--- a/rocm-dev/rd-open
+++ b/rocm-dev/rd-open
@@ -28,15 +28,17 @@ if ! docker run -it `
         `--cap-add=SYS_PTRACE `
         `--security-opt seccomp=unconfined `
         `--name $instance_name_rd `
-        `--hostname $(hostname -s)/$instance_name_rd `
+        `--hostname $(get_host_alias)/$instance_name_rd `
         `$image_name_rd > /dev/null; then
     die "fail to run: $image_name_rd"
 fi
 
 if (( $# == 0 )); then
     # default: enter docker
-    if ! docker exec -it "$instance_name_rd" bash; then
-        die "fail: exec $instance_name_rd"
+    docker exec -it "$instance_name_rd" bash
+    ret_code=$?
+    if (( ret_code != 0 )); then
+        log "docker exec $instance_name_rd return fail code ($ret_code)"
     fi
     close_container "$instance_name_rd"
 fi
diff --git a/solver/sv-open b/solver/sv-open
--- a/solver/sv-open
+++ b/solver/sv-open
@@ -29,13 +29,15 @@ if ! docker run -it `
         `--security-opt seccomp=unconfined `
         `-p 127.0.0.1:9346:9339 `
         `--name $instance_name_sv `
-        `--hostname $(hostname -s)/$instance_name_sv `
+        `--hostname $(get_host_alias)/$instance_name_sv `
         `$image_name_rd > /dev/null; then
     die "fail to run: $image_name_sv"
 fi
 
 # default: enter docker
-if ! docker exec -it "$instance_name_sv" bash; then
-    die "fail: exec $instance_name_sv"
+docker exec -it "$instance_name_sv" bash
+ret_code=$?
+if (( ret_code != 0 )); then
+    log "docker exec $instance_name_sv return fail code ($ret_code)"
 fi
 close_container "$instance_name_sv"
