create sv docker

diff --git a/rocm-dev/rd-open b/rocm-dev/rd-open
--- a/rocm-dev/rd-open
+++ b/rocm-dev/rd-open
@@ -33,9 +33,10 @@ if ! docker run -it `
     die "fail to run: $image_name_rd"
 fi
 
-# default: enter docker
-if ! docker exec -it "$instance_name_rd" bash; then
-    die "fail: exec $instance_name_rd"
+if (( $# == 0 )); then
+    # default: enter docker
+    if ! docker exec -it "$instance_name_rd" bash; then
+        die "fail: exec $instance_name_rd"
+    fi
+    close_container "$instance_name_rd"
 fi
-
-close_container "$instance_name_rd"
diff --git a/scripts/util/repo-helper b/scripts/util/repo-helper
--- a/scripts/util/repo-helper
+++ b/scripts/util/repo-helper
@@ -69,3 +69,32 @@ function ls_uid() {
     printf "rocm_branch:\t%s\n" "$rocm_branch"
     printf "rocm_build:\t%s\n"  "$rocm_build"
 }    
+
+function get_rocm_ver() {
+    local unified_build=$1
+    local api_url
+    if (( unified_build >= 100000 )); then
+        # new server: api v2
+        api_url="http://bas.amd.com/api/v2/get/builds?ubid="
+    else
+        # old server: api v1
+        api_url="http://mkdcvlnxapp01.amd.com/api/get/builds.php?unified_id="
+    fi
+
+    local response=$(curl -s -w ",%{http_code}" ${api_url}${unified_build}) || ret_code=$?
+    if (( ret_code != 0 )); then
+        echo "failed to parser build ${unified_build} with code $ret_code"
+        exit 1
+    fi
+
+    http_content=${response%,*}
+    http_ret=${response##*,}
+
+    if (( http_ret != 200 )); then
+        echo "fail to get $unified_build ($http_content)"
+        exit 1
+    fi
+
+    jq -r '.builds[] | select(.build_type == "ROCm") | .build_version' <<< ${http_content}
+    return 0
+}
diff --git a/solver/sv-open b/solver/sv-open
--- a/solver/sv-open
+++ b/solver/sv-open
@@ -34,17 +34,8 @@ if ! docker run -it `
     die "fail to run: $image_name_sv"
 fi
 
-# enter or run setup
-if (( $# == 0 )); then
-    # default: enter docker
-    if ! docker exec -it "$instance_name_sv" bash; then
-        die "fail: exec $instance_name_sv"
-    fi
-else 
-    # solver setup
-    if ! docker exec -it "$instance_name_sv" bash -c "cd ../shisa;${rdh_root}/shisa/s-setup"; then
-        die "fail: setup solver"
-    fi
+# default: enter docker
+if ! docker exec -it "$instance_name_sv" bash; then
+    die "fail: exec $instance_name_sv"
 fi
-
 close_container "$instance_name_sv"
