add shisa deployment

diff --git a/scripts/util/tools b/scripts/util/tools
--- a/scripts/util/tools
+++ b/scripts/util/tools
@@ -211,6 +211,21 @@ function permute() {
     return 0
 }
 
+function extract() {
+    local src_file=$1
+    local target=$2
+
+    # unpack src from windows/p4v
+    refresh_dir "$target"
+    if ! tar -xzvf "$src_file" -C "$target"; then
+        die "fail: unpack $src_file"
+    fi
+
+    # enable scripts
+    enable_scripts "$target"
+    return 0
+}
+
 function enable_scripts() {
     local dir=$1
     if ! check_tool dos2unix dos2unix deb; then
diff --git a/shisa/s-unpack-src b/shisa/s-unpack-src
--- a/shisa/s-unpack-src
+++ b/shisa/s-unpack-src
@@ -15,10 +15,16 @@ if is_inside_docker; then
     die "fail: cannot run inside docker!"
 fi
 
-# unpack src from windows/p4v
-if ! tar -xvf shisa_src.tar.gz; then
-    die "fail: unpack shisa_src.tar.gz"
+src_file="./shisa_src.tar.gz"
+if (( $# == 1 )); then
+    src_file=$1
 fi
 
-# enable scripts
-enable_scripts .
+target="./shisa"
+if (( $# == 2 )); then
+    src_file=$1
+fi
+
+if ! extract "$src_file" "$target"; then
+    die "fail: unpack $src_file to $target"
+fi
