gpu interface setup

diff --git a/shisa/gi-docker-build b/shisa/gi-docker-build
--- a/shisa/gi-docker-build
+++ b/shisa/gi-docker-build
@@ -21,11 +21,11 @@ fi
 docker_file="${rdh_root}/dockerfile/gpu_interface.dockerfile"
 
 # docker build
-log "docker build: $image_name"
-if ! docker build -t "$image_name" `
+log "docker build: $image_name_gi"
+if ! docker build -t "$image_name_gi" `
                  `-f $docker_file `
                  `--build-arg ROCM_VERSION=$rocm_version `
                  `--build-arg ROCM_OS_VERSION=$rocm_os_version .; then
-    die "fail to build: $image_name"
+    die "fail to build: $image_name_gi"
 fi
-log "docker build success: $image_name"
+log "docker build success: $image_name_gi"
diff --git a/shisa/gi-run b/shisa/gi-run
--- a/shisa/gi-run
+++ b/shisa/gi-run
@@ -29,15 +29,14 @@ if ! docker run -it `
         `--group-add video `
         `--cap-add=SYS_PTRACE `
         `--security-opt seccomp=unconfined `
-        `--name $instance_name `
-        `--hostname $instance_name `
-        `-e CONTAINER_NAME=$instance_name `
-        `$image_name > /dev/null; then
-    die "fail to run: $image_name"
+        `--name $instance_name_gi `
+        `--hostname $instance_name_gi `
+        `$image_name_gi > /dev/null; then
+    die "fail to run: $image_name_gi"
 fi
 
 # activate rdh
-if ! docker exec "$instance_name" `
+if ! docker exec "$instance_name_gi" `
             `bash -c "echo 'source ${rdh_root}/activate' >> /root/.bashrc"; then
     die "fail: rdh activate"
 fi
@@ -45,20 +44,20 @@ fi
 # enter or run setup
 if (( $# == 0 )); then
     # default: enter docker
-    if ! docker exec -it "$instance_name" bash; then
-        die "fail: exec $instance_name"
+    if ! docker exec -it "$instance_name_gi" bash; then
+        die "fail: exec $instance_name_gi"
     fi
 else 
     # run g-setup
-    if ! docker exec -it "$instance_name" bash -c "${rdh_root}/shisa/gi-setup"; then
+    if ! docker exec -it "$instance_name_gi" bash -c "${rdh_root}/shisa/gi-setup"; then
         die "fail: setup gpu-interface"
     fi
 fi
 
-if ! docker stop "$instance_name"; then
-    die "fail: stop $instance_name"
+if ! docker stop "$instance_name_gi"; then
+    die "fail: stop $instance_name_gi"
 fi
 
-if ! docker rm "$instance_name"; then
-    die "fail: rm $instance_name"
+if ! docker rm "$instance_name_gi"; then
+    die "fail: rm $instance_name_gi"
 fi
diff --git a/shisa/gi-setup b/shisa/gi-setup
--- a/shisa/gi-setup
+++ b/shisa/gi-setup
@@ -132,9 +132,9 @@ function setup_gi() {
     popd
 }
 
-# run inside docker instance of $instance_name
-if ! is_docker_instance $instance_name; then
-    die "fail: please run it at instance: $instance_name"
+# run inside docker instance of $instance_name_gi
+if ! is_docker_instance $instance_name_gi; then
+    die "fail: please run it at instance: $instance_name_gi"
 fi
 
 setup_rocr rocr
@@ -146,4 +146,4 @@ find rocr -name "libhsa-runtime64.a" | xargs realpath
 
 # libgpu_interface.11.so
 log "======================results: gpu_interface=================="
-find "$SHISA" -name "libgpu_interface.11.so"
+find "$SHISA" -name "libgpu_interface.*.so"
