deploy script

diff --git a/shisa/gi-run b/shisa/gi-run
--- a/shisa/gi-run
+++ b/shisa/gi-run
@@ -1,12 +1,12 @@
 #!/usr/bin/bash
-# make tools available
+rdh_root="$(realpath $0|xargs dirname)/.."
+source ${rdh_root}/activate
+
+# expose self
 bin_dir=$(realpath $0|xargs dirname)
-util_dir=$(dirname $bin_dir)/scripts/util
-PATH=${bin_dir}:${util_dir}:$PATH
 SELF_TAG="[$(basename $0)]"
 
 # import tools
-source tools
 source docker-helper
 source gi-config
 
@@ -15,24 +15,50 @@ if is_inside_docker; then
     die "fail: cannot run inside docker!"
 fi
 
-# launch gpu interface
-docker run -it --rm `
-        `-v ${HOME}/work/il/SHISA_min:/SHISA/. `
+# launch gpu-interface in background
+if ! docker run -it `
+        `--detach `
+        `-v ${HOME}/work/shisa:/SHISA/. `
         `-e SHISA=/SHISA `
         `-v ${HOME}/work:${HOME}/work `
         `-v ${HOME}/work/.ssh:/root/.ssh `
-        `-v ${HOME}/work/vscode-server:/root/.vscode-server `
+        `-v ${HOME}/.vscode-server:/root/.vscode-server `
         `--device=/dev/kfd `
         `--device=/dev/dri `
-        `-w ${HOME}/work/il/ `
+        `-w ${HOME}/work `
         `--group-add video `
         `--cap-add=SYS_PTRACE `
         `--security-opt seccomp=unconfined `
         `--name $instance_name `
         `--hostname $instance_name `
         `-e CONTAINER_NAME=$instance_name `
-        `$image_name
-
-if (( $? != 0 )); then
+        `$image_name > /dev/null; then
     die "fail to run: $image_name"
+fi
+
+# activate rdh
+if ! docker exec "$instance_name" `
+            `bash -c "echo 'source ${rdh_root}/activate' >> /root/.bashrc"; then
+    die "fail: rdh activate"
+fi
+
+# enter or run setup
+if (( $# == 0 )); then
+    # default: enter docker
+    if ! docker exec -it "$instance_name" bash; then
+        die "fail: exec $instance_name"
+    fi
+else 
+    # run g-setup
+    if ! docker exec -it "$instance_name" bash -c "${rdh_root}/shisa/gi-setup"; then
+        die "fail: setup gpu-interface"
+    fi
+fi
+
+if ! docker stop "$instance_name"; then
+    die "fail: stop $instance_name"
+fi
+
+if ! docker remove "$instance_name"; then
+    die "fail: remove $instance_name"
 fi
diff --git a/shisa/s-run b/shisa/s-run
--- a/shisa/s-run
+++ b/shisa/s-run
@@ -1,12 +1,11 @@
 #!/usr/bin/bash
-# make tools available
+rdh_root="$(realpath $0|xargs dirname)/.."
+source ${rdh_root}/activate
+
+# expose self
 bin_dir=$(realpath $0|xargs dirname)
-util_dir=$(dirname $bin_dir)/scripts/util
-PATH=${bin_dir}:${util_dir}:$PATH
-SELF_TAG="[$(basename $0)]"
 
 # import tools
-source tools
 source docker-helper
 source s-config
 
@@ -18,19 +17,47 @@ fi
 #        `-e SHISA_HSA_PM4_MODE=1 `
 #        `-e SHISA_HSA_TIMEOUT_SECONDS=1 `
 
-docker run -it --rm `
-        `-v ${HOME}/work/il/SHISA_min:/SHISA/. `
+# launch shisa in background
+if ! docker run -it `
+        `--detach `
+        `-v ${HOME}/work/shisa:/SHISA/. `
         `-v ${HOME}/work:${HOME}/work `
         `-v ${HOME}/work/vscode-server:/root/.vscode-server `
         `-w ${HOME}/work/misa `
         `-e LD_LIBRARY_PATH=/SHISA/bin-hip-6.5/:/SHISA/bin:/opt/rocm/lib/llvm/lib `
+        `-e SHISA_HSA_PM4_MODE=1 `
         `-p 127.0.0.1:9346:9339 `
         `--device=/dev/kfd `
         `--device=/dev/dri `
         `--name $instance_name `
         `--hostname $instance_name `
-        `$image_name
-
-if (( $? != 0 )); then
+        `$image_name > /dev/null; then
     die "fail to run: $image_name"
+fi
+
+# activate rdh
+if ! docker exec "$instance_name" `
+            `bash -c "echo 'source ${rdh_root}/activate' >> /root/.bashrc"; then
+    die "fail: rdh activate"
+fi
+
+# enter or run setup
+if (( $# == 0 )); then
+    # default: enter docker
+    if ! docker exec -it "$instance_name" bash; then
+        die "fail: exec $instance_name"
+    fi
+else 
+    # shisa setup
+    if ! docker exec -it "$instance_name" bash -c "cd ../shisa;${rdh_root}/shisa/s-setup"; then
+        die "fail: setup shisa"
+    fi
+fi
+
+if ! docker stop "$instance_name"; then
+    die "fail: stop $instance_name"
+fi
+
+if ! docker remove "$instance_name"; then
+    die "fail: remove $instance_name"
 fi
diff --git a/shisa/shisa-deploy-linux b/shisa/shisa-deploy-linux
--- a/shisa/shisa-deploy-linux
+++ b/shisa/shisa-deploy-linux
@@ -4,7 +4,7 @@ rdh_root="$(realpath $0|xargs dirname)/.."
 source ${rdh_root}/activate
 
 # expose self
-bin_dir=$(realpath $0|xargs dirname)
+bin_dir="$(realpath $0|xargs dirname)"
 SELF_TAG="[$(basename $0)]"
 
 # import tools
@@ -12,29 +12,61 @@ source docker-helper
 source s-config
 source m-config
 
-function shisa_deploy_linux() {
-    #1: unpack src
+function deploy_linux() {
+    # step 1: get shisa src
     log "1. ++++++++++++++++++++ unpack shisa src +++++++++++++++++"
     local src_file="$1"
     local target="$(realpath "$src_file" | xargs dirname)"/shisa
+    refresh_dir "$target"
     if ! s-unpack-src "$src_file" "$target"; then
         die "fail: unpack $src_file to $target"
     fi
     log "++++++++++++++++++++ unpack shisa src: succ +++++++++++++++++"
 
-    # step2: build gpu-interface docker
-    log "2. ++++++++++++++++++++ build gpu interface docker +++++++++++++++++"
+    # step 2: get misa source
+    refresh_dir "./misa"
+    log "2. ++++++++++++++++++++ misa setup +++++++++++++++++"
+    pushd "./misa"
+    if ! m-setup;  then
+        die "fail: misa setup"
+    fi
+
+    # apply patch
+    cd "$misa_branch"
+    if ! git apply "$misa_dir/op_sel.patch"; then
+        die "fail: apply misa patch ob_sel.patch"
+    fi
+
+    popd
+    log "2. ++++++++++++++++++++ misa setup: sucess +++++++++++++++++"
+
+    # step 3: build gpu-interface docker
+    log "3. ++++++++++++++++++++ build gpu interface docker +++++++++++++++++"
     if ! gi-docker-build; then
         die "fail: build gpu_interface docker"
     fi
-    log "2. ++++++++++++++++++++ build gpu interface docker: succ +++++++++++++++++"
-
-    # step3: build shisa docker
-    log "3. ++++++++++++++++++++ build gpu interface docker +++++++++++++++++"
-    if ! s-docker-build; then
-        die "fail: build gpu_interface docker"
-    fi
     log "3. ++++++++++++++++++++ build gpu interface docker: succ +++++++++++++++++"
+
+    # step 4: build shisa docker
+    log "4. ++++++++++++++++++++ build shisa docker +++++++++++++++++"
+    if ! s-docker-build; then
+        die "fail: build shisa docker"
+    fi
+    log "4. ++++++++++++++++++++ build shisa docker: succ +++++++++++++++++"
+
+    # step 5: gpu-interface setup
+    log "5. ++++++++++++++++++++ gpu-interface setup +++++++++++++++++"
+    if ! gi-run setup; then
+        die "fail: gi-run gpu-interface"
+    fi
+    log "5. ++++++++++++++++++++ gpu-interface setup: sucess +++++++++++++++++"
+
+    # step 6: shisa setup
+    log "6. ++++++++++++++++++++ shisa setup +++++++++++++++++"
+    if ! s-run setup; then
+        die "fail: s-run setup shisa doker"
+    fi
+    log "6. ++++++++++++++++++++ shisa setup: sucess +++++++++++++++++"
 
     return 0
 }
@@ -45,4 +77,4 @@ if is_inside_docker; then
 fi
 
 # deploy shisa in ./shisa
-shisa_deploy_linux "./shisa_src.tar.gz"
+deploy_linux "./shisa_src.tar.gz"
