update s-setup and gi-setup

diff --git a/shisa/gi-setup b/shisa/gi-setup
--- a/shisa/gi-setup
+++ b/shisa/gi-setup
@@ -37,18 +37,17 @@ function setup_rocr() {
     return 0
 }
 
-function setup_gi() {
+function clone_gi() {
     local target=$1
-    local rocr_path=$2
 
     if ! refresh_dir "$target"; then
         die "fail to create: $target"
     fi
 
     # setup to store pat 
-    if ! git config --global credential.helper store; then
-        die "fail: git credential store"
-    fi
+    # if ! git config --global url."git@github.com:".insteadOf "https://github.com/"; then
+    #    die "fail: git credential store"
+    #fi
 
     # clone gpu_interface and sub modules(pal_navi, pal_vega)
     local branch_opt
@@ -56,11 +55,36 @@ function setup_gi() {
         branch_opt="-b ${gi_branch}"
     fi
 
-    if ! git clone --recurse-submodules https://$gh_user:$pat@github.amd.com/LibAmd/SHISA_gpu_interface $branch_opt $target; then
-        die "fail to clone: https://$gh_user:$pat@github.amd.com/LibAmd/SHISA_gpu_interface"
+    if ! git clone git@github.com:LibAmd/SHISA_gpu_interface.git $branch_opt $target; then
+        die "fail to clone: https://github.amd.com/LibAmd/SHISA_gpu_interface"
     fi
 
-    pushd $target
+    # clone dependency: ./drivers at https://github.com/AMD-Radeon-Driver/drivers.git
+    pushd "$target"
+    if ! git init drivers; then
+        die "fail to init drivers"
+    fi
+
+    cd drivers
+    if ! git sparse-checkout set drivers/pxproxy drivers/inc/asic_reg drivers/inc/shared drivers/dx/dxx/vam; then
+        die "fail to sparse-checkout from drivers"
+    fi
+
+    if ! git remote add origin git@github.com:AMD-Radeon-Driver/drivers.git; then
+        die "fail to add origin repo"
+    fi
+
+    if ! git pull --depth 1 origin amd/release/23.30; then
+        die "fail to pull amd/release/23.30 from drivers"
+    fi
+    mv drivers/pxproxy drivers/inc drivers/dx/dxx/vam .
+    cd ..
+
+
+    if ! git submodule update --init; then
+        die "fail: update submodules"
+    fi
+
     # apply patch to pal_navi 
     cd pal_navi
     if ! git apply ../0001-PAL_CLIENT_SHISA.pal_navi.patch; then
@@ -70,7 +94,7 @@ function setup_gi() {
     fi
 
     # fix syntax errors in pal_navi/shared/devdriver/shared/legacy/inc/util/queue.h
-    sed -i 's/\(: Queue(rhs\.\)allocCb\()\)/\1m_allocCb\2/' ./shared/devdriver/shared/legacy/inc/util/queue.h
+    # sed -i 's/\(: Queue(rhs\.\)allocCb\()\)/\1m_allocCb\2/' ./shared/devdriver/shared/legacy/inc/util/queue.h
 
     # fix syntax error in pal_navi/shared/devdriver/third_party/rapidjson/include/rapidjson/document.h
     sed -i 's/const SizeType length;/SizeType length;/' ./shared/devdriver/third_party/rapidjson/include/rapidjson/document.h
@@ -82,68 +106,56 @@ function setup_gi() {
     else
         git status
     fi
+    if ! git submodule update --init; then
+        die "fail: update submodules"
+    fi
 
-    # clone dependency: ./drivers at https://github.amd.com/AMD-Radeon-Driver/drivers.git
+    # change Developer-Solutions to AMD-Developer-Solutions in .gitmodules
+    sed -i 's/Developer-Solutions/AMD-Developer-Solutions/' shared/devdriver/.gitmodules
     cd ..
-    if ! git init drivers; then
-        die "fail to init drivers"
+    if ! git submodule update --init --recursive; then
+        die "fail: update submodules"
     fi
-    cd drivers
-    
-    if ! git sparse-checkout set drivers/pxproxy drivers/inc/asic_reg drivers/inc/shared drivers/dx/dxx/vam; then
-        die "fail to sparse-checkout from drivers"
-    fi
+    return 0
+}
 
-    if ! git remote add origin https://github.amd.com/AMD-Radeon-Driver/drivers.git; then
-        die "fail to add origin repo"
-    fi
-
-    if ! git pull --depth 1 origin amd/release/23.30; then
-        die "fail to pull amd/release/23.30 from drivers"
-    fi
-    mv drivers/pxproxy drivers/inc drivers/dx/dxx/vam .
-    cd ..
-
-    # patch amd_comgr.h
-    #if [ ! -f /opt/rocm-$rocm_version_gi/include/amd_comgr/amd_comgr.h ]; then
-    #    die "file not exist: /opt/rocm-$rocm_version_gi/include/amd_comgr/amd_comgr.h"
-    #fi
-    #cp /opt/rocm-$rocm_version_gi/include/amd_comgr/amd_comgr.h ./external/amd_comgr
+function build_gi() {
+    local target=$1
 
     mkdir -p /SHISA/bin /SHISA/binDebug
-    # release
+    pushd $target
     if ! cmake_build . `
                 `Release `
                 `-DGPU_INTERFACE_PAL_SUPPORT=ON `
-                `-DGPU_INTERFACE_HSA_SUPPORT=ON `
-                `-DHSA_STATIC_LIBRARY=${rocr_path}/build-release/runtime/hsa-runtime/libhsa-runtime64.a; then
+                `-DGPU_INTERFACE_HSA_SUPPORT=ON; then
         die "fail: build release gpu_interface"
     fi
 
-    # debug
     if ! cmake_build . `
                 `Debug `
                 `-DGPU_INTERFACE_PAL_SUPPORT=ON `
-                `-DGPU_INTERFACE_HSA_SUPPORT=ON `
-                `-DHSA_STATIC_LIBRARY=${rocr_path}/build-debug/runtime/hsa-runtime/libhsa-runtime64.a; then
+                `-DGPU_INTERFACE_HSA_SUPPORT=ONS; then
         die "fail: build debug gpu_interface"
     fi
-
     popd
 }
 
-# run inside docker instance of $instance_name_gi
-if ! is_docker_instance $instance_name_gi; then
-    die "fail: please run it at instance: $instance_name_gi"
+
+# no dependency on libhsa-runtime64.a anymore.
+# setup_rocr 
+
+if [[ "$1" == "1" ]]; then
+    clone_gi gpu_interface
+else
+    # run inside docker instance of $instance_name_gi
+    if ! is_docker_instance $instance_name_gi; then
+        die "fail: please run it at instance: $instance_name_gi"
+    fi
+
+    build_gi gpu_interface
+
+    # libgpu_interface.<version>.so
+    log "======================results: gpu_interface=================="
+    find "$SHISA" -name "libgpu_interface.*.so"
 fi
-
-setup_rocr rocr
-setup_gi gpu_interface "$(realpath rocr)"
-
-# libhsa-runtime64.a
-log "======================results: rocr=================="
-find rocr -name "libhsa-runtime64.a" | xargs realpath
-
-# libgpu_interface.11.so
-log "======================results: gpu_interface=================="
-find "$SHISA" -name "libgpu_interface.*.so"
+exit 0
diff --git a/shisa/shisa-deploy-linux b/shisa/shisa-deploy-linux
--- a/shisa/shisa-deploy-linux
+++ b/shisa/shisa-deploy-linux
@@ -57,14 +57,18 @@ function deploy_linux() {
     log "4. ++++++++++++++++++++ build shisa docker: succ +++++++++++++++++"
 
     popd
-    rmdir -rf "$tmp_dir"
+    rm -rf "$tmp_dir"
 
     # step 5: gpu-interface setup
     log "5. ++++++++++++++++++++ gpu-interface setup +++++++++++++++++"
+    if ! gi-setup 1; then
+        die "fail: clone gpu-interface"
+    fi
+
     if ! gi-open setup; then
         die "fail: gi-open gpu-interface"
     fi
-    log "5. ++++++++++++++++++++ gpu-interface setup: sucess +++++++++++++++++"
+    log "5. ++++++++++++++++++++ gpu-isnterface setup: sucess +++++++++++++++++"
     sudo chown -R ${USER}:${USER} $target/bin $target/binDebug
 
     # step 6: shisa setup
