rocm-dev and solver

diff --git a/solver/sv-open b/solver/sv-open
--- a/solver/sv-open
+++ b/solver/sv-open
@@ -7,12 +7,15 @@ bin_dir=$(realpath $0|xargs dirname)
 
 # import tools
 source docker-helper
-source s-config
+source sv-config
 
 # run at host
 if is_inside_docker; then
     die "fail: cannot run inside docker!"
 fi
+
+# close old instance
+close_container "$instance_name_sv"
 
 #        `-e SHISA_HSA_PM4_MODE=1 `
 #        `-e SHISA_HSA_TIMEOUT_SECONDS=1 `
@@ -24,19 +27,18 @@ if ! docker run -it `
         `-v ${HOME}/work/shisa:/SHISA/. `
         `-v ${HOME}/work:${HOME}/work `
         `-v ${HOME}/work/vscode-server:/root/.vscode-server `
-        `-w ${HOME}/work/misa `
-        `-e LD_LIBRARY_PATH=/SHISA/bin:/opt/rocm/lib/llvm/lib `
+        `-w ${HOME}/work `
         `-p 127.0.0.1:9346:9339 `
         `--device=/dev/kfd `
         `--device=/dev/dri `
-        `--name $instance_name `
-        `--hostname $instance_name `
-        `$image_name > /dev/null; then
-    die "fail to run: $image_name"
+        `--name $instance_name_sv `
+        `--hostname $instance_name_sv `
+        `$image_name_sv > /dev/null; then
+    die "fail to run: $image_name_sv"
 fi
 
 # activate rdh
-if ! docker exec "$instance_name" `
+if ! docker exec "$instance_name_sv" `
             `bash -c "echo 'source ${rdh_root}/activate' >> /root/.bashrc"; then
     die "fail: rdh activate"
 fi
@@ -44,20 +46,14 @@ fi
 # enter or run setup
 if (( $# == 0 )); then
     # default: enter docker
-    if ! docker exec -it "$instance_name" bash; then
-        die "fail: exec $instance_name"
+    if ! docker exec -it "$instance_name_sv" bash; then
+        die "fail: exec $instance_name_sv"
     fi
 else 
     # shisa setup
-    if ! docker exec -it "$instance_name" bash -c "cd ../shisa;${rdh_root}/shisa/s-setup"; then
+    if ! docker exec -it "$instance_name_sv" bash -c "cd ../shisa;${rdh_root}/shisa/s-setup"; then
         die "fail: setup shisa"
     fi
 fi
 
-if ! docker stop "$instance_name"; then
-    die "fail: stop $instance_name"
-fi
-
-if ! docker rm "$instance_name"; then
-    die "fail: rm $instance_name"
-fi
+close_container "$instance_name_sv"
